Repository googleapis/sphinx-docfx-yaml, pull requests merged in 2021-05, with the labels that each got.

#14 chore: Authsynth synthtool update
  .pre-commit-config.yaml
  synth.metadata
Labels: cla: yes, context: none

#16 feat: clarify names in the left nav
  docfx_yaml/extension.py
Labels: cla: yes, type: feature request

#20 test: add GitHub Action config for testing
  .github/workflows/ci.yaml
  .gitignore
  README.rst
  tox.ini
Labels: cla: yes, type: process

#22 feat: shorten function names shown on pages
  docfx_yaml/extension.py
Labels: cla: yes

#17 chore: pick up changes from Synthool
  .pre-commit-config.yaml
  synth.metadata
Labels: cla: yes, context: none

#26 chore(deps): use RenovateBot for Sphinx versioning
  requirements.txt
Labels: cla: yes, type: feature request

#33 chore: exclude .gitignore from template updates
  synth.py
Labels: cla: yes, type: cleanup

#35 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: cla: yes
